### ISSUE TITLE
Poor predictions when running the provided models

### ISSUE THREAD

**Issue by abailoni** [sartorius-research/LIVECell#3]
Hello,

Over the last few days I have been trying to test some of the models you trained on some different microscopy images. However, I am encountering some problems while running the model.

To check that everything works, I tried to evaluate the model on the test data you provide, but (no matter which model I choose, I tried both with anchor-based and anchor-free models), I always get very wrong predictions, almost as if the models were not trained at all. I attached a picture below as an example. I also tried with images from the training set and results are the same. This is also confirmed by the evaluation script, which returns very low AP scores. I broke my head few days over this to understand what I could possibly do wrong, but I could not solve the problem (I also checked multiple times to make sure that I am passing the correct MODEL.WEIGHTS parameter for the LIVECell model).

Am I the only one facing this problem or did someone else manage to run the provided models?

Thank you!

Here there are few things I noticed while running the script:

- The script raises the following warning. Is it a problem or is it expected?
```shell
[09/22 16:57:37 fvcore.common.checkpoint]: Loading checkpoint from /scratch/bailoni/datasets/LIVECell/LIVECell_anchor_based_skbr3_model.pth
WARNING [09/22 16:57:38 fvcore.common.checkpoint]: 'roi_heads.box_head.0.fc1.weight' has shape (1024, 12544) in the checkpoint but (1024, 50176) in the model! Skipped.
WARNING [09/22 16:57:38 fvcore.common.checkpoint]: 'roi_heads.box_head.1.fc1.weight' has shape (1024, 12544) in the checkpoint but (1024, 50176) in the model! Skipped.
WARNING [09/22 16:57:38 fvcore.common.checkpoint]: 'roi_heads.box_head.2.fc1.weight' has shape (1024, 12544) in the checkpoint but (1024, 50176) in the model! Skipped.
[09/22 16:57:38 fvcore.common.checkpoint]: Some model parameters are not in the checkpoint:
  roi_heads.box_head.0.fc1.weight
  roi_heads.box_head.2.fc1.weight
  roi_heads.box_head.1.fc1.weight
[09/22 16:57:38 fvcore.common.checkpoint]: The checkpoint contains parameters not used by the model:
  pixel_mean
  pixel_std
```
- Here there is an examples of the scores I get:
```shell
[09/22 16:58:42 d2.evaluation.coco_evaluation_LIVECell]: Evaluation results for bbox:
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 0.081 | 0.336  | 0.010  | 0.020 | 0.453 | 0.027 |
Loading and preparing results...
DONE (t=0.07s)
creating index...
index created!
Size parameters: [[0, 10000000000.0], [0, 324], [324, 961], [961, 10000000000.0]]
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=40.64s).
Accumulating evaluation results...
DONE (t=0.12s).
In method
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=2000 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=2000 ] = 0.004
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=2000 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=2000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=2000 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=2000 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=500 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=2000 ] = 0.019
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=2000 ] = 0.007
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=2000 ] = 0.049
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=2000 ] = 0.016
_derive_coco_results
[09/22 16:59:23 d2.evaluation.coco_evaluation_LIVECell]: Evaluation results for segm:
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 0.151 | 0.384  | 0.078  | 0.029 | 1.126 | 0.166 |
[09/22 16:59:23 d2.engine.defaults]: Evaluation results for TEST in csv format:
[09/22 16:59:23 d2.evaluation.testing]: copypaste: Task: bbox
[09/22 16:59:23 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[09/22 16:59:23 d2.evaluation.testing]: copypaste: 0.0807,0.3364,0.0104,0.0201,0.4529,0.0274
[09/22 16:59:23 d2.evaluation.testing]: copypaste: Task: segm
[09/22 16:59:23 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[09/22 16:59:23 d2.evaluation.testing]: copypaste: 0.1508,0.3836,0.0783,0.0293,1.1261,0.1664
```
- As you can see in the attached image, the predictions are not totally random (most of the instances are predicted where there is indeed a cell), but they are not accurate at all and way too many
- In the provided `coco_evaluation.py` script I had to comment out the last section of the code (*Added code to produce precision and recall for all iou levels / Chris*, [line 650](https://github.com/sartorius-research/LIVECell/blob/e39ca3bb1d467077f43589ec250819566854d9a6/code/coco_evaluation.py#L650)) because it was giving several errors (the first one complaining that an integer is not iterable, at line 656)
- I noticed that the input tensor passed to the model has a much larger shape (800, 1083, 3) than the original image shape (520, 704, 3), but I guess this is normal (the output masks have indeed the correct shape (520, 704))

![instances](https://user-images.githubusercontent.com/16247286/134467861-ec2beb70-ec8a-4eea-ac29-9c0574b9b161.png)

**Comment by ChristofferEdlund** [comment]
Hi there @abailoni!
Could you provide the command you use to run the evaluation and what config file you are using so we can figure this out together?

**Comment by abailoni** [comment]
Thanks for the quick reply @ChristofferEdlund !

This is the config I am using:

```yaml
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "/scratch/bailoni/datasets/LIVECell/LIVECell_anchor_based_model.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 0
  MASK_ON: True
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 200
    STRIDE_IN_1X1: False
    RADIX: 2
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3,Res4,Res5
    DEFORM_MODULATED: True
    DEFORM_NUM_GROUPS: 2
    NORM: "SyncBN"

  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[4], [9], [17], [31], [64], [127]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.25, 0.5, 1.0, 2.0, 4.0]]  # Three aspect ratios (same for all in feature maps)
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 512
    NAME: CascadeROIHeads
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    NUM_CONV: 8
    NORM: "SyncBN"
  RPN:
    IN_FEATURES: ["p2" ,"p2", "p3", "p4", "p5", "p6"]
    BATCH_SIZE_PER_IMAGE: 256
    POST_NMS_TOPK_TEST: 3000
    POST_NMS_TOPK_TRAIN: 3000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 12000
  RETINANET:
    NUM_CLASSES: 1
    TOPK_CANDIDATES_TEST: 3000
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [11.578, 11.578, 11.578]
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (17500, 20000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 500
DATASETS:
  TRAIN: ("TRAIN",)  #REPLACE TRAIN WITH THE REGISTERED NAME 
  TEST: ("TEST",)    #REPLACE TRAIN WITH THE REGISTERED NAME
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
INPUT:
  MIN_SIZE_TRAIN: (440, 480, 520, 560, 580, 620)

  CROP:
    ENABLED: False
  FORMAT: "BGR"
TEST:
  DETECTIONS_PER_IMAGE: 3000 # 1000
  EVAL_PERIOD: 500
  PRECISE_BN:
    ENABLED: False
  AUG:
    ENABLED: False
OUTPUT_DIR: "/scratch/bailoni/projects/LIVECell/ancorbased_out_3" # PATH TO SAVE THE OUTPUT RESULTS
DATALOADER:
  NUM_WORKERS: 8
VERSION: 2
```

Since this is an anchor-based model, I installed the `detectron2-ResNeSt` repo and modified the `train_net.py` by adding the following lines at the beginning:

```python
from detectron2.evaluation.coco_evaluation_LIVECell import COCOEvaluator
from detectron2.data.datasets import register_coco_instances
root_dir = "/scratch/bailoni/datasets/LIVECell/"
register_coco_instances("TEST", {}, os.path.join(root_dir, "0_train2percent.json"),
                        os.path.join(root_dir, "images/livecell_train_val_images"))
register_coco_instances("TRAIN", {}, os.path.join(root_dir, "livecell_coco_train.json"),
                        os.path.join(root_dir, "images/livecell_train_val_images"))
```

To make the script run faster (since the model is detecting so many instances, the evaluation takes very long), I set up a smaller version of the train set as TEST. The paths in `0_train2percent.json` expects all images in the same directory, so I had to put them all in `images/livecell_train_val_images` (without being divided in subdirectories).

To run the script, I run:

`python train_net.py --config-file {path-to-config-file-shown-above} --eval-only`


This is the full config printed by the script:

```yaml
[09/23 15:05:27 detectron2]: Running with full config:
CUDNN_BENCHMARK: False
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: ()
  PROPOSAL_FILES_TRAIN: ()
  TEST: ('TEST',)
  TRAIN: ('TRAIN',)
GLOBAL:
  HACK: 1.0
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.9, 0.9]
    TYPE: relative_range
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (440, 480, 520, 560, 580, 620)
  MIN_SIZE_TRAIN_SAMPLING: choice
MODEL:
  ANCHOR_GENERATOR:
    ANGLES: [[-90, 0, 90]]
    ASPECT_RATIOS: [[0.25, 0.5, 1.0, 2.0, 4.0]]
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES: [[4], [9], [17], [31], [64], [127]]
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_resnet_fpn_backbone
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    NORM: SyncBN
    OUT_CHANNELS: 256
  KEYPOINT_ON: False
  LOAD_PROPOSALS: False
  MASK_ON: True
  META_ARCHITECTURE: GeneralizedRCNN
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [11.578, 11.578, 11.578]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    AVD: False
    AVG_DOWN: False
    BOTTLENECK_WIDTH: 64
    DEEP_STEM: False
    DEFORM_MODULATED: True
    DEFORM_NUM_GROUPS: 2
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEPTH: 200
    NORM: SyncBN
    NUM_GROUPS: 1
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    RADIX: 2
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
   STRIDE_IN_1X1: False
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.4, 0.5]
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 1
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 3000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS: ((10.0, 10.0, 5.0, 5.0), (20.0, 20.0, 10.0, 10.0), (30.0, 30.0, 15.0, 15.0))
    IOUS: (0.5, 0.6, 0.7)
  ROI_BOX_HEAD:
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    CLS_AGNOSTIC_BBOX_REG: True
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FastRCNNConvFCHead
    NORM: SyncBN
    NUM_CONV: 4
    NUM_FC: 1
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    IOU_LABELS: [0, 1]
    IOU_THRESHOLDS: [0.5]
    NAME: CascadeROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 1
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: True
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS: (512, 512, 512, 512, 512, 512, 512, 512)
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: True
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
    CONV_DIM: 256
    NAME: MaskRCNNConvUpsampleHead
    NORM: SyncBN
    NUM_CONV: 8
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    BOUNDARY_THRESH: -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES: ['p2', 'p2', 'p3', 'p4', 'p5', 'p6']
    IOU_LABELS: [0, -1, 1]
    IOU_THRESHOLDS: [0.3, 0.7]
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
     POST_NMS_TOPK_TEST: 3000
    POST_NMS_TOPK_TRAIN: 3000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 12000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    LOSS_WEIGHT: 1.0
    NAME: SemSegFPNHead
    NORM: GN
    NUM_CLASSES: 54
  WEIGHTS: /scratch/bailoni/datasets/LIVECell/LIVECell_anchor_based_model.pth
OUTPUT_DIR: /scratch/bailoni/projects/LIVECell/ancorbased_out_3
SEED: -1
SOLVER:
  BASE_LR: 0.02
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 500
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: False
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 30000
  MOMENTUM: 0.9
  STEPS: (17500, 20000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: False
    FLIP: True
    MAX_SIZE: 4000
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
  DETECTIONS_PER_IMAGE: 3000
  EVAL_PERIOD: 500
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
```
